### PR TITLE
Revert to original response

### PR DESCRIPTION
**Pull request by froi**
A similar PR may already be submitted!
Please search among the [Pull request](../) before creating one.

Thanks for submitting a pull request! Please provide enough information so that others can review your pull request:

For more information, see the `CONTRIBUTING` guide.

**Summary**

The response for the languages endpoint was changed in a counterproductive way. This change aims to revert the endpoint to have the original response

This PR fixes/implements the following **bugs/features**

* [x] Breaking changes

Explain the **motivation** for making this change. What existing problem does the pull request solve?

The response for the languages endpoint was changed in a counterproductive way. This change aims to revert the endpoint to have the original response

**Test plan (required)**

### CODE REVIEW

**Comment by froi** [comment]
Not to be merges before the clean up PR get approved #308

**Comment by froi** [comment]
@saracope Friendly ping for your attention 😄

**Comment by saracope** [comment]
@froi Does the CI always fail on these? Is that something I need to ask BJ to look at?

**Comment by froi** [comment]
**CircleCI**

Integration tests will sometimes fail because of timeouts or execution issues. On occasions running just the integration tests will solve it.

**Code Climate**

These are the eternal struggle on this project. Depending on the code added I would sometimes approve them in Code Climate and assume the technical debt. The real symptom is that tests need to be improved.

**Recommendation**

I would totally have BJ look at them. At the very least it will help him familiarize himself with the code faster.

**Comment by saracope** [comment]
Pinging @bjbhatt for review.

**Comment by froi** [comment]
Hello fine peeps. A friendly ping about this. I'd like to get it out of my PRs.

**Pull request merged**
