### PR TITLE
removed unneeded nodemon and event-stream

### PR DESCRIPTION
**Pull request by DanielJDufour**
A similar PR may already be submitted!
Please search among the [Pull request](../) before creating one.

Thanks for submitting a pull request! Please provide enough information so that others can review your pull request:

For more information, see the `CONTRIBUTING` guide.

**Summary**

This PR fixes/implements the following **bugs/features**

* [ ] Removed two unneeded packages that caused users to download (but not execute) a vulnerable version of event-stream

Explain the **motivation** for making this change. What existing problem does the pull request solve?
Cybersecurity.

### CODE REVIEW

**Comment by DanielJDufour** [comment]
@froi , CircleCI is down again.  Could you test locally and confirm this works?
image

**Comment by DanielJDufour** [comment]
I manually triggered CircleCI build and it appears to be running

**Comment by DanielJDufour** [comment]
NVM: CircleCI isn't running them:
image

**Comment by froi** [comment]
Thanks for the PR @DanielJDufour. I'll test this and if all is good will merge or give feedback.

**Comment by froi** [comment]
Working great, thanks @DanielJDufour

**Pull request merged**
